"""Build BookCRM.html: the whole app in one file that runs in a browser with no install.

Inlines the CSS/JS from static/, the SQLite engine (sql.js, WebAssembly) and the
in-browser backend (standalone/localapi.js). Schema and option lists are taken from
the Python source so both versions stay identical.

    python build_standalone.py      ->  BookCRM.html
"""
import base64
import json
import os
import re

from crm import constants as C
from crm.db import DEFAULT_SETTINGS, SCHEMA

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "BookCRM.html")


def read(*parts, mode="r"):
    with open(os.path.join(ROOT, *parts), mode, **({} if "b" in mode else {"encoding": "utf-8"})) as f:
        return f.read()


def script(code):
    # Keep inline code from closing the <script> tag early.
    return "<script>\n" + code.replace("</script", "<\\/script") + "\n</script>"


def main():
    html = read("static", "index.html")
    wasm_b64 = base64.b64encode(read("standalone", "vendor", "sql-wasm.wasm", mode="rb")).decode("ascii")
    config = {
        "schema": SCHEMA,
        "lookups": C.lookups(),
        "default_settings": DEFAULT_SETTINGS,
        "default_commission": C.DEFAULT_COMMISSION,
        "default_doc_templates": C.DEFAULT_DOC_TEMPLATES,
        "default_carriers": C.DEFAULT_CARRIERS,
        "default_account_types": C.DEFAULT_ACCOUNT_TYPES,
    }
    boot = (
        "window.CRM_CONFIG = " + json.dumps(config) + ";\n"
        "window.CRM_CONFIG.wasm = function () {\n"
        f"  var b = atob('{wasm_b64}');\n"
        "  var u = new Uint8Array(b.length);\n"
        "  for (var i = 0; i < b.length; i++) u[i] = b.charCodeAt(i);\n"
        "  return u;\n"
        "};"
    )

    html = html.replace('<link rel="stylesheet" href="/static/css/style.css">',
                        "<style>\n" + read("static", "css", "style.css") + "\n</style>")

    first = True

    def inline(m):
        nonlocal first
        src = m.group(1).lstrip("/").split("/", 1)[1]  # static/js/... -> js/...
        parts = []
        if first:  # engine + local backend go before the app scripts
            parts += [script(boot), script(read("standalone", "vendor", "sql-wasm.js")), script(read("standalone", "localapi.js"))]
            first = False
        parts.append(script(read("static", *src.split("/"))))
        return "\n".join(parts)

    html = re.sub(r'<script src="([^"]+)"></script>', inline, html)
    assert 'src="/static' not in html and 'href="/static' not in html, "unresolved static reference"
    html = html.replace("<title>Book CRM</title>", "<title>Book CRM</title>\n  <!-- Generated by build_standalone.py - do not edit by hand -->")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(html)
    print(f"Wrote {OUT} ({os.path.getsize(OUT) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
